# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6673a5e4c43b8405697981f43394337ed4ea7d49247a44ffb4ab83a0647202a1805597a829e2d89b1a1a19be19bbf948f09c73806a8fa270092533c52cebd2f1

test:
  secret_key_base: 9a500f78d442c03c042eb82c5a91ac6aab71b46a27c86e7cadf8fbebed5ddd0f0a203850f9485e1bb9ad0711d34571d42598e9e13771995fe4b8f909020bbae3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
